import React from "react";

const texasInventory = [
  {
    id: 1,
    title: "HPS Flood Light Bulb",
    vendorPartNum: "Reox 67516 LU150/55/ECO",
    manufacturerPartNum: "67516 LU150/55/ECO",
    description: "HPS Flood Light Bulb SYL 67516 LU150/55/ECO",
    brand: "Osram",
    leadTime: "1-3 weeks ex works",
    price: 19.53,
    image: "texas-inventory/mini.jpg",
  },
  {
    id: 2,
    title: "HPS Flood Light Bulb",
    vendorPartNum: "Reox67578 LU250/ECO",
    manufacturerPartNum: "67578 LU250/ECO",
    description: "HPS Flood Light Bulb SYL 67578 LU250/ECO",
    brand: "Osram",
    leadTime: "1-3 weeks ex works",
    price: 21.4,
    image: "texas-inventory/mini.jpg",
  },
  {
    id: 3,
    title: "Daylight (white) Flourescent Light",
    vendorPartNum: "Reox 21718 FO17865XP/ECO",
    manufacturerPartNum: "21718 FO17865XPECO",
    description: "Daylight (white) Flourescent Light SYL 21718 FO17865XPECO",
    brand: "Osram",
    leadTime: "1-3 weeks ex works",
    price: 4.28,
    image: "texas-inventory/bulb.jpg",
  },
  {
    id: 4,
    title: "Daylight (white) Flourescent Light",
    vendorPartNum: "Reox 24811 FO32865/ECO",
    manufacturerPartNum: "24811 FO32865ECO",
    description: "Daylight (white) Flourescent Light SYL 24811 FO32865ECO",
    brand: "Osram",
    leadTime: "1-3 weeks ex works",
    price: 4.35,
    image: "texas-inventory/bulb.jpg",
  },
  {
    id: 5,
    title: "Hawke Junction Box for 63A Receptacle Welding Socket",
    vendorPartNum: "HK63A",
    manufacturerPartNum: "",
    description:
      "Junction Box for 63A Receptacle Welding Socket Junction Box for 63A Receptacle Welding Socket Cct Type:PL630, 208W, 690V, 63A, IECEx, IP66, Tamb -50oC – + 40oC.",
    brand: "Hawke",
    leadTime: " 5-7 Weeks ex works",
    price: 532.84,
    image: "texas-inventory/Hawke-Junction-Box.jpg",
  },
  {
    id: 6,
    title:
      "Hawke Secondary Junction Box (JB) for lighting fittings with two incoming cable entry of M20 and four outgoing cable entry of M20",
    vendorPartNum: "HK20",
    manufacturerPartNum: "",
    description:
      "Secondary Junction Box (JB) for lighting fittings with two incoming cable entry of M20 and four outgoing cable entry of M20 Eexe (Type M, 10 off beige terminal suitable for 2.5 to 16mm2 conductor lighting fittings or Series GBX161609, or D69412, UI 690V, IP66, IECEx, -20oC – +55oC",
    brand: "Hawke",
    leadTime: " 5-7 Weeks ex works",
    price: 640.24,
    image: "texas-inventory/box.jpg",
  },
  {
    id: 7,
    title:
      "Hawke Lighting Circcuit Primary Junction Box (JB) with three incoming cable entry of M25 and six outgoing cable entry of M20",
    vendorPartNum: "HK2520",
    manufacturerPartNum: "",
    description:
      "Lighting Circcuit Primary Junction Box (JB) with three incoming cable entry of M25 and six outgoing cable entry of M20 Eexe (Type M, 10 off beige terminal suitable for 2.5 to 16mm2 conductor for 1XHP flood lighting and type N, 16 off beige terminal suitable for 2.5 to 16mm2 conductor for 3 and 4XHP flood lighting fittings or Type:PL630, 208W, 690V, 63A, IECEx, IP66, Tamb -50oC – + 40oC. ",
    brand: "Hawke",
    leadTime: " 5-7 Weeks ex works",
    price: 711.41,
    image: "texas-inventory/box.jpg",
  },
  {
    id: 8,
    title: "CEAG Heater Safety Disconnection Switch",
    vendorPartNum: "Re-0266",
    manufacturerPartNum: "0266",
    description:
      "Heater Safety Disconnection Switch GHG262 2301 R007 UI 500V, IN 20A, AC 20A, IP66, Ex rated",
    brand: "CEAG",
    leadTime: "12 Weeks ex works",
    price: 2059.96,
    image: "texas-inventory/switch.jpg",
  },
  {
    id: 9,
    title:
      "Complete Suit-ARC flash Suit/Glove/sleeves/Arc flash helmet Face shield",
    vendorPartNum: "RE-S576",
    manufacturerPartNum: "SFX576",
    description:
      "Complete Suit-ARC flash Suit/Glove/sleeves/Arc flash helmet Face shield , SFX576 – Complete 40cal kit inc.holdall",
    brand: "",
    leadTime: "",
    price: null,
    image: "texas-inventory/completeppe.jpg",
  },
  {
    id: 10,
    title: "LNL-1320-S3B LENEL DUAL READER INTERFACE MODULE",
    vendorPartNum: "RE-20-SB LENEL",
    manufacturerPartNum: "LNL-1320-S3B LENEL",
    description: "LNL-1320-S3B LENEL DUAL READER INTERFACE MODULE",
    brand: "",
    leadTime: "",
    price: null,
    image: "texas-inventory/board.jpg",
  },
  {
    id: 11,
    title: "ATEX Emergency door release",
    vendorPartNum: "REL-ATXAP3A",
    manufacturerPartNum: "",
    description: "ATEX Emergency door release GNEXCP6CBGSSLAP3A1RL24",
    brand: "",
    leadTime: "",
    price: null,
    image: "texas-inventory/es2.jpg",
  },
  {
    id: 12,
    title: "Green Weatherproof Manual Call Point",
    vendorPartNum: "REL-DMN0GE",
    manufacturerPartNum: "DMN700GE",
    description:
      "Green Weatherproof Manual Call Point – Emergency Door Release Convention",
    brand: "",
    leadTime: "",
    price: null,
    image: "texas-inventory/es2.jpg",
  },
  {
    id: 13,
    title: "Green Weatherproof Manual Call Point",
    vendorPartNum: "REL-DMN0GE",
    manufacturerPartNum: "DMN700GE",
    description:
      "Green Weatherproof Manual Call Point – Emergency Door Release Convention",
    brand: "",
    leadTime: "",
    price: "",
    image: "texas-inventory/alert.jpg",
  },
  {
    id: 14,
    title: "PROX POINT PLUS READER BLACK",
    vendorPartNum: "REL-BKB00",
    manufacturerPartNum: "6005BKB00",
    description:
      "PROX POINT PLUS READER BLACK HID 6005BKB00 ProxPoint Plus Proximity Card Reader with Wiegand Output, Pigtail, Beep On, LED Normally Red, Reader Flashes Green on Tag Read, Black",
    brand: "HID",
    leadTime: "",
    price: null,
    image: "texas-inventory/hid.jpg",
  },
  {
    id: 15,
    title: "Ethernet Surge Protector",
    vendorPartNum: "REL-S8P-1U",
    manufacturerPartNum: "SPG-8P-1U",
    description: "Ethernet Surge Protector 8P PoE 1U Gigabit Brand Cyberteam",
    brand: "HID",
    leadTime: "",
    price: null,
    image: "texas-inventory/alert.jpg",
  },
  {
    id: 16,
    title: "Ethernet Surge Protector",
    vendorPartNum: "REL-S8P-1U",
    manufacturerPartNum: "SPG-8P-1U",
    description: "Ethernet Surge Protector 8P PoE 1U Gigabit Brand Cyberteam",
    brand: "HID",
    leadTime: "",
    price: null,
    image: "texas-inventory/ethernet.jpg",
  },
  {
    id: 17,
    title: "STAINLESS STEEL WELDED PIPE",
    vendorPartNum: "",
    manufacturerPartNum: "",
    description:
      "STAINLESS STEEL WELDED PIPE Standand & Grade: ASTM A312 GR304 OD (inch): 3/4 OD (mm): 26.67 WT (mm): 1.25 Length (m): 3.00 Theoretical Weight (ton/m): 0.00078362",
    brand: "",
    leadTime: "",
    price: null,
    image: "texas-inventory/pipe.jpg",
  },
  {
    id: 18,
    title: "Ironwear 4509IR",
    vendorPartNum: "REL4509IR",
    manufacturerPartNum: "4509IR",
    description:
      "Ironwear 4509IR Ironwear 4509IR | Class 3 49” Black Bottom Raincoat w/Tuckaway Hood & Black Soil Shield Part Number: 4509IR-L-2XL Item Weight: 1.96 pounds Package Dimensions: 6.14 x 12.52 x 2.32 inches Item model number: 4509IR Style: Ironwear 9511 Material: Polyester Pattern: Solid Special Features: high-visibility 100% Polyester DESIGNED FOR SAFETY | This high-visibility raincoat is a Class 3 garment with 2” silver reflective tape over the shoulders and across the arms and torso for protection that meets or exceeds ANSI 107 standards COMFORT & UTILITY | At 49 inches long, the waterproof polyester / polyurethane material is sturdy but lightweight, with grommeted vents under the arms and across the torso so you can comfortably endure hazardous weather and low visibility conditions INTEGRATED COMPONENTS | 2 radio clips, a vertical badge tab, 2 large front pockets, and hook and loop wrist fasteners help you do your job more efficiently. EASY CLEAN AND CARE | This raincoat is designed to be easily cleaned with a damp cloth after use; do NOT machine wash, dry clean, or heat dry",
    brand: "",
    leadTime: "",
    price: null,
    image: "texas-inventory/ppe.jpg",
  },
  {
    id: 19,
    title: "DRYCODE Mens Rubber Waterproof Boots D-3425",
    vendorPartNum: "RELD-3425",
    manufacturerPartNum: "D-3425",
    description:
      "DRYCODE Mens Rubber Waterproof Boots D-3425 D DRYCODE Work Boots for Men with Steel Shank, Waterproof Rubber Boots, Warm 6mm Neoprene Anti Slip Durable Rain Boots, Black, Size 5-14 Package Dimensions: 16.14 x 12.64 x 4.92 inches; 5.18 Pounds Department: Unisex-adult",
    brand: "",
    leadTime: "",
    price: 107.86,
    image: "texas-inventory/longsafetyshoe.jpg",
  },
  {
    id: 20,
    title: "ORU PFD Life Jacket OR90U",
    vendorPartNum: "RELOR90U",
    manufacturerPartNum: "OR90U",
    description:
      "ORU PFD Life Jacket | Water Safety Vest, Coast Guard Approved, NRS US Coast Guard Type: III, Adjustable Fit, Unisex, Lightweight, High Mobility, Material: 400-denier Ripstop Nylon, Size: XS/M Brand: Oru Kayak Color: Grey Age Range (Description) : Adult Life Vest Type :Type III Material: Nylon WATER SAFETY FOR EVERYONE: Safety first! We never kayak without a PFD—and neither should you. The Oru PFD is made by NRS, the industry leader in high-performance kayaking gear. Protect yourself during water sports like kayaking, stand up paddling, rafting and more. MAXIMUM SAFETY: The NRS Clearwater is a type III, medium-profile l ife jacket delivering 16.5 pounds of flotation. Our safety Vest is Coast Guard approved and will keep you safe on water. ADJUSTABLE FIT: Six adjustment points secure a customizable fit and high mobility while the front-entry zipper allows to slipping the jacket on and off easily. Two large zippered pockets, a lashtab, and 3M reflective accents throughout make sure you are visible even in low-light. ULTRA DURABLE: The 400 denier nylon fabric construction ensures durability through seasons of wear and tear. PRODUCT SPECS: Weight: 1.75lbs. XS/M Chest Size: 30 – 42 in. US Coast Guard Type: III. Profile: Medium. Design Floatation: 16.5lbs. Outer Fabric: 400-denier ripstop nylon. Entry System: Front zip. Pockets: 2-Front Lash Tab: 1-Front. Adjustment System: 4 – Side, 2 – Shoulder",
    brand: "",
    leadTime: "",
    price: 82.8,
    image: "texas-inventory/bodyshield.jpg",
  },
  {
    id: 21,
    title: "3M 4168",
    vendorPartNum: "REL4168",
    manufacturerPartNum: "4168",
    description:
      "3M 4168 Full Face Reusable Respirator, Gray, Large Description 3M™ 4168Full Facepiece Reusable Respirator, Gray Color, Large Size – 1 Each The 3M™ 4168 Full Facepiece Reusable Respirator offers reliable and convenient respiratory protection and is suitable for many situations, helping provide protection against particulates and a wide variety of gases and vapors. Featuring a soft lightweight facepiece that makes for a comfortable all day wear with adjustable features that help provide a secure, personalized fit. Additionally, when properly fitted and used with approved 3M™ cartridges and filters, this respirator helps provide protection at concentrations up to 10 times the Permissible Exposure Limit (PEL). The 3M™ 6000 Half Facepiece Series is NIOSH approved for negative-pressure air purifying and positive-pressure dual airline applications.",
    brand: "3M",
    leadTime: "",
    price: 201.71,
    image: "texas-inventory/headset.jpg",
  },
  {
    id: 22,
    title: "3M Peltor PO95H3",
    vendorPartNum: "RELPO95H3",
    manufacturerPartNum: "PO95H3",
    description:
      "3M Peltor PO95H3 Optime 95 Helmet Attachable Earmuff, Hearing Protection, Ear Protectors, NRR 21dB, Ideal for machine shops and power tools Product Dimensions: 5.13 x 7.38 x 3.75 inches; 10.24 ounces Department: unisex-adult",
    brand: "3M",
    leadTime: "",
    price: 25.2,
    image: "texas-inventory/headset.jpg",
  },
  {
    id: 23,
    title: "3M™ E-A-R™ UltraFit™ Ear Plugs W53M",
    vendorPartNum: "RELW53M",
    manufacturerPartNum: "W53M",
    description:
      "3M™ E-A-R™ UltraFit™ Ear Plugs W53M Description UltraFit™ reusable ear plugs are durable and feature a triple-flange, push-to-fit design to provide comfort and convenience. Easy to wash with soap and water so they can be used multiple times, reducing waste. Push-to-fit style for easy and hygienic fit Universal size fits comfortably in most ear canals Premolded, triple-flange ear plug design inserts easily No roll-down necessary Soft polymer is washable and reusable Compliance 3M™ ear plugs must be used in accordance with OSHA regulations, and the user instructions, warnings, and limitations accompanying each product.",
    brand: "3M",
    leadTime: "",
    price: 657.12,
    image: "texas-inventory/ear.jpg",
  },
  {
    id: 24,
    title: "Bolt Eye Visor 7369",
    vendorPartNum: "REL7369",
    manufacturerPartNum: "7369",
    description:
      "Bolt Eye Visor – Clear Dual Coat Lens for Milwaukee Hard Hat/Helmet Standard Features The MILWAUKEE 7369 BOLT Eye Visor is designed to provide you with the best fit and easy headlamp use. These Z87.1+ eye visors are classified as spectacles and can be used in place of safety glasses. The eye visor pivots and adjusts to provide a comfortable and secure fit for a wide variety of face shapes. The eye visor includes a BOLT Low-Profile Headlamp Mount that allows seamless compatibility with most headlamps. Each eye visor is treated with a fog-free interior coating and an anti-scratch exterior hard coating for longer product lifetimes. This eye visor is part of the BOLT System which allows users to Secure Accessories Simultaneously. This eye visor secures into the BOLT front mount of all MILWAUKEE safety helmets and hard hats.",
    brand: "Bolt",
    leadTime: "",
    price: 131.99,
    image: "texas-inventory/whiteglass.jpg",
  },
  {
    id: 25,
    title: "Sellstrom 391105",
    vendorPartNum: "REL391105",
    manufacturerPartNum: "391105",
    description:
      "Sellstrom S30110 Sellstrom Advantage Series Face Shield – Clear Window with Aluminum Binding – Comfortable Ratcheting Headgear, ANSI Z87.1+ (391105) Product Dimensions: 16.5 x 9.96 x 5.91 inches Item model number: 391105 Department: unisex-adult FULL PROTECTION: Clear face mask safety shield for men and women to guard face and eyes. Versatile and for a variety of uses in industrial and home settings like welding, cutting, grinding and woodworking FACE SHIELD FEATURES: Includes a grey abs crown, uncoated clear polycarbonate window with aluminum binding and ratchet headgear and pin closure. Abs injection molded crowns have universal bracket pin pattern for use with any window mount NO ASSEMBLY NEEDED: The 301 Advantage series arrives fully assembled. Just remove the protective film from both sides of face shield before using SAFETY APPLICATIONS: According to the CDC, there are 2,000 eye injuries a day at U.S. workplaces. Protect yourself and use for construction, manufacturing, oil & gas, metal work, and more ANSI/ISEA Z87.1 STANDARDS: Certified to prevent work injuries from impact, non-ionizing radiation, and chemical exposure from machinery and other types of face hazards",
    brand: "",
    leadTime: "",
    price: 20.48,
    image: "texas-inventory/shield.jpg",
  },
  {
    id: 26,
    title: "OPTIFENSE 5454WS",
    vendorPartNum: "REL5454WS",
    manufacturerPartNum: "5454WS",
    description:
      "OPTIFENSE 5454WS OPTIFENSE™ DVP2’s are essential safety goggles when eye protection is required. Whether in a lab, manufacturing, or construction setting, DVP2 is your choice for eye safety. Meets the ANSI Z87+ standard and OSHA compliant Antifog and anti-scratch lens coating with UV protection Ergonomic frame with soft rubber seal and adjustable band Wide angle design to reduce optical distortion (does not fit over prescription glasses)",
    brand: "",
    leadTime: "",
    price: 38.39,
    image: "texas-inventory/eagleglasses.jpg",
  },
  {
    id: 27,
    title: "Goggles G15XQ",
    vendorPartNum: "RELG15XQ",
    manufacturerPartNum: "G15XQ",
    description:
      "Goggles for impact and high temperature protection G15XQ Glass marking: 2C-3/5-3.1 U 1 FT K N CE Grey-green polycarbonate eyepiece, 180° field of view Optical Class 1 Soft elastomer nose bridge Nylon frame, metal and green gis Soft temples, adjustable length, adjustable tilt Rubber camber, rocking Ventilation system above the screen",
    brand: "",
    leadTime: "",
    price: 19.4,
    image: "texas-inventory/glassess.jpg",
  },
  {
    id: 28,
    title: "Gloves, Cut level, Lanzi LANC10",
    vendorPartNum: "RELLANC10",
    manufacturerPartNum: "LANC10",
    description:
      "Gloves, Cut level LANC10, Lanzi Cut-resistant lev. C seamless ISO-SKIN GLOVE, yellow/black mélange liner, black Hi-Foam coating on palm Product information Weight 0.055 kg Measurements 0 x 0 x 0 cm Sales unit pair GTIN / EAN 8056994530100 Item code GIS844RP_10&LANZI",
    brand: "",
    leadTime: "",
    price: 15.7,
    image: "texas-inventory/2glove.jpg",
  },
  {
    id: 29,
    title: "Juba Therma-Oil Neoprene Gloves 388JT",
    vendorPartNum: "RELL388JT",
    manufacturerPartNum: "388JT",
    description:
      "Juba Therma-Oil Neoprene Gloves EN388/407/374 388JT Juba Therma-Oil Neoprene Gloves EN388/407/374 388JT Gloves with good grip in dry, wet and oiled environments. Flexible and comfortable. Contact heat resistance (250°C for 15”). Special for use with hot liquids and splashes. Sanitized® sanitizing function protects gloves against fungus, mites and bacteria, prevents odors, provides long-lasting polymer protection of the material and minimizes skin irritation. Individual neutral pocket. Glove recommended for long-lasting heavy-duty work such as petrochemicals, oil refineries, laboratory analysis, special chemicals, electronics, ferrous metal casting, pump and compressor manufacture; wood processing; mineral production; railway transport; cold industry, frozen food transfer and work with hot liquids.",
    brand: "",
    leadTime: "",
    price: 20.48,
    image: "texas-inventory/greenblack.jpg",
  },
  {
    id: 30,
    title: "Portwest Anti Vibration Glove – PA75VG",
    vendorPartNum: "RELPA75VG",
    manufacturerPartNum: "PA75VG",
    description:
      "Portwest Anti Vibration Glove – PA75VG Portwest Anti Vibration Glove – PA75VG Specially designed to reduce the effects of impact and vibration. Excellent levels of comfort and dexterity when using powertools, jack hammers, concrete breakers etc. 10 gauge. Portwest Workwear. Anti Vibration Glove – PA75VG. Reduces effects of impact & vibration High levels of comfort & dexterity Safety Standards: EN 420 || AS/NZS 2161 .2 ||AS/NZS 2161 .3 || EN 10819 (TRm = 0.865 TRh = 0.598) || EN 388:2016 – 4.1.4.2.X Material/Fabric: 50% Cotton, 45% Nylon, 5% Rubber yarn.",
    brand: "",
    leadTime: "",
    price: 24.83,
    image: "texas-inventory/greenblack.jpg",
  },
  {
    id: 31,
    title: "Ansell HyFlex™ AHF11 Medium Duty Abrasion-Resistant Gloves",
    vendorPartNum: "RELAHF11",
    manufacturerPartNum: "AHF11",
    description:
      "Ansell HyFlex™ AHF11 Medium Duty Abrasion-Resistant Gloves, INTERCEPT™ Technology Description Level C cut protection gloves offer enhanced abrasion resistance for extended wear. INTERCEPT Technology™ for high level of cut protection High durability PU coating, increased levels of abrasion resistance Dirt masking design allows for extended product use In compliance with the standards EN420 (General requirements) and EN388 (Mechanical hazards)",
    brand: "hyflex",
    leadTime: "",
    price: 14.02,
    image: "texas-inventory/hyflex.jpg",
  },
  {
    id: 32,
    title: "Cut-Resistant Gloves AHF10",
    vendorPartNum: "RELAHF10",
    manufacturerPartNum: "AHF10",
    description:
      "Ansell® HyFlex® AHF10 Gray ANSI A6 Cut-Resistant Gloves Description The Ansell® HyFlex® 74-048 Gray Cut Resistant Gloves are extremely cut resistant, with an ANSI cut rating of A6, for superior protection. These DSM Dyneema® core constructed gloves meet ANSI industry standards in both cut and abrasion. They are heavy duty gloves with a lightweight feel, allowing for maximum flexibility and productivity, without cumbersome, awkward fabric inhibiting the user. They also feature an extended cuff to fit tightly with added comfort and keep hands protected and safe while working. This pair of gloves is made out of dirt-masking gray fabric. These gloves provide ideal protection for metal fabrication, food processing, and automotive industries. Features an extended cuff to fit tightly and provide optimal protection Heavy-duty with lightweight feel allowing for maximum flexibility and productivity DSM Dyneema® core construction, providing high-weight protection Ideal for metal fabrication, food processing, or automotive industries Meets industry standards ANSI 4 (Abrasion), ANSI A6 (Cut)",
    brand: "",
    leadTime: "",
    price: 16.12,
    image: "texas-inventory/glovebrow.jpg",
  },
  {
    id: 33,
    title: "COMMANDER IMPACT™, HPPE/Glass/Steel CI7760",
    vendorPartNum: "RELCI7760",
    manufacturerPartNum: "CI7760",
    description:
      "COMMANDER IMPACT™, HPPE/Glass/Steel CI7760 Description High-performance polyethylene (HPPE) gloves with added steel and/or glass fibers offer an increased cut resistance over gloves made with HPPE only. The CORDOVA-brand COMMANDER IMPACT™ glove offers ANSI/ISEA A7 cut level protection. It features a 13-gauge, hi-vis yellow HPPE/Glass/Steel fiber shell with a two-layer, red, sandy nitrile palm coating for added gripping power. It provides soft TPR for impact protection and a hook and loop closure. View all COMMANDER-brand gloves. LOW LIGHT PROTECTION: Hi-Vis Yellow EXCELLENT STRENGTH & DEXTERITY: 13-Gauge HPPE/Glass/Steel Fiber Shell STRONG GRIP: Two-Layer, Red, Sandy Nitrile Palm Coating IMPACT PROTECTION: Soft TPR ADDED WEAR PROTECTION: Reinforced Thumb Crotch ADJUSTABLE: Hook & Loop Closure ANSI-RATED PROTECTION: Cut, Abrasion, Puncture, Impact Sizes: S-3XL Certification/Rating: ANSI/ISEA 105-2016 Cut Level A7: 4503 grams ANSI/ISEA 105-2016 Abrasion Level 6; Puncture Level 4 ANSI 138-2019: Impact Level 2",
    brand: "",
    leadTime: "",
    price: 30.85,
    image: "texas-inventory/gloveyell.jpg",
  },
  {
    id: 34,
    title: "CLASS 4 RUBBER GLOVES AR290",
    vendorPartNum: "RELAR290",
    manufacturerPartNum: "AR290",
    description:
      "CLASS 4 RUBBER GLOVES AR290 Description Experience unparalleled safety with Armadillo Armor Class 4 Insulated Rubber Gloves. These cutting-edge electrical-insulating rubber gloves are meticulously crafted to conform to the stringent ASTM D120 Class 4 standards. Safeguarding workers against voltages up to 36,000VAC, these gloves serve as armor to protect against electrical hazards, ensuring unyielding safety. WARNING: It is imperative to align the voltage class rating of your gloves to the applicable voltage when performing work. SPECIFICATIONS Class: 4 Size: 8, 9, 10, 11 Outer Color: Black Inner Color: Red Length: 16″, 18″ Material: Natural Rubber Standards: ASTM D 120, IEC EN60903 AC Max. Use Voltage: 36000V AC Proof Test Voltage (AC): 40000V AC Type: Type I Cuff Style: ST Includes: Pair, Left and Right",
    brand: "",
    leadTime: "",
    price: 369.4,
    image: "texas-inventory/thickblackglovepin.jpg",
  },
  {
    id: 35,
    title: "CLASS 3 RUBBER GLOVES AR280",
    vendorPartNum: "RELAR280",
    manufacturerPartNum: "AR280",
    description:
      "CLASS 3 RUBBER GLOVES AR280 Description Experience unparalleled safety with Armadillo Armor Class 3 Insulated Rubber Gloves. These cutting-edge electrical-insulating rubber gloves are meticulously crafted to conform to the stringent ASTM D120 Class 3 standards. Safeguarding workers against voltages up to 26500VAC, these gloves serve as armor to protect against electrical hazards, ensuring unyielding safety. WARNING: It is imperative to align the voltage class rating of your gloves to the applicable voltage when performing work. SPECIFICATIONS Class: 3 Size: 8, 9, 10, 11 Outer Color: Black Inner Color: Red Length: 16″, 18″ Material: Natural Rubber Standards: ASTM D 120, IEC EN60903 AC Max. Use Voltage: 26500V AC Proof Test Voltage (AC): 30000V AC Type: Type I Cuff Style: ST Includes: Pair, Left and Right",
    brand: "",
    leadTime: "",
    price: 263.4,
    image: "texas-inventory/thickblackglovegre.jpg",
  },
  {
    id: 36,
    title: "CLASS 2 RUBBER GLOVES AR270",
    vendorPartNum: "RELAR270",
    manufacturerPartNum: "AR270",
    description:
      "CLASS 2 RUBBER GLOVES AR270 Description Experience unparalleled safety with Armadillo Armor Class 2 Insulated Rubber Gloves. These cutting-edge electrical-insulating rubber gloves are meticulously crafted to conform to the stringent ASTM D120 Class 2 standards. Safeguarding workers against voltages up to 17000VAC, these gloves serve as armor to protect against electrical hazards, ensuring unyielding safety. WARNING: It is imperative to align the voltage class rating of your gloves to the applicable voltage when performing work. SPECIFICATIONS Class: 2 Size: 8, 9, 10, 11 Outer Color: Black Inner Color: Red Length: 14″, 16″, 18″ Material: Natural Rubber Standards: ASTM D 120, IEC EN60903 AC Max. Use Voltage: 17000V AC Proof Test Voltage (AC): 20,000V AC Type: Type I Cuff Style: ST Includes: Pair, Left and Right",
    brand: "",
    leadTime: "",
    price: 155.4,
    image: "texas-inventory/thickblackglove.jpg",
  },
  {
    id: 37,
    title:
      "Insulated Electrical Glove Kit Class 1 14″ Length – 7,500V AC SI70E",
    vendorPartNum: "RELSI70E",
    manufacturerPartNum: "SI70E",
    description:
      "Insulated Electrical Glove Kit Class 1 14″ Length – 7,500V AC SI70E Description Salisbury linemen’s gloves are extremely flexible to make working with small parts easy. Class 1 Color options: Black Gloves meet or exceed ASTM D120 and IEC EN60903 Standards. 14″ length Max use: 7,500 VAC Sizing Salisbury linemen’s gloves are available in a full range of sizes, from 7 through 12, including half sizes (there are no 7 ½ and 11 ½). To determine glove size, measure the circumference around the palm in inches. Allow for additional room if fabric glove liners are to be worn, especially with thermal liners Leather Protectors Salisbury goatskin leather protectors with non-metallic buckle and pull strap for class 1 14″ length rubber gloves. Leather Protector Gloves should always be worn over Insulating Rubber Gloves to provide the needed mechanical protection against cuts, abrasions and punctures. The ILP3S Series is manufactured from top grain goatskin. Comes in dual sizes 7/7.5 through 11/11.5 and 12.",
    brand: "",
    leadTime: "",
    price: 261.37,
    image: "texas-inventory/70e.jpg",
  },
  {
    id: 38,
    title: "Electrical Safety Gloves REL 4432",
    vendorPartNum: "REL4432",
    manufacturerPartNum: "4432",
    description:
      "Description Fully insulated gloves test stamped for working voltages 1000V AC / 1500V DC The EN/IEC 60903 standards advise a visual inspection by inflation of the glove in order to detect air leaks. This can be carried out by the pneumatic glove tester These gloves must be used with leather over gloves, to ensure protection against damage. We would also recommend using these with cotton under gloves for extra cleanliness Material: Natural Latex Supplied in an individual UV-resistant bag CATEGORY RC = A + Z + C + H (resistant to acid, oil-resistant, ozone, and very low temperatures) Thickness: 1mm Length: 360mm Sizes 8,9,10,11,12 available Note: Neutral or Red gloves may be issued",
    brand: "",
    leadTime: "",
    price: 117.63,
    image: "texas-inventory/glovebutter.jpg",
  },
  {
    id: 39,
    title: "Westchester Top Grain Cowhide W/ Gauntlet Cuff Gloves W980",
    vendorPartNum: "RELW980",
    manufacturerPartNum: "W980",
    description:
      "Westchester Top Grain Cowhide W/ Gauntlet Cuff Gloves W980 Premium top-grain cowhide leather used for the palm Natural white canvas back Great for general applications 4.5-inch rubberized gauntlet cuffs for extra protection Features pull tab and winged thumb Recommended for railroad work, masonry and woodworking",
    brand: "",
    leadTime: "",
    price: 103.2,
    image: "texas-inventory/kitchenglove.jpg",
  },
  {
    id: 40,
    title: "Red PVC gloves JR403",
    vendorPartNum: "RELJR403",
    manufacturerPartNum: "JR403",
    description:
      "Red PVC gloves, plain, 40 cm JR403 Mrigold Flexiproof 40 cm The glove is ideal for intensive tasks, handling of abrasive and sharp components, immersion in very aggressive chemicals, including solvents. contact heat up to 100°C Description – Glove made of over-plasticized PVC bath on a 100% cotton jersey knit base. – Specially designed for general purpose mechanical and chemical work requiring high resistance to immersion in acids, bases, petroleum and derivatives with high mechanical resistance to abrasion and tearing. – The ergonomic shape of the hand ensures a perfect natural fit. – High degree of flexibility. Excellent mechanical strength. – EN 420: General requirements- EN 388: Protection against Mechanical Hazards: * ABRASION:4 * CUT:1 * TEAR:2 * PERFORATION:1 – Packaging: Packs of 12 pairs.",
    brand: "Juba",
    leadTime: "",
    price: 7.2,
    image: "texas-inventory/glovebrown.jpg",
  },
  {
    id: 41,
    title:
      "Marigold Flexiproof 40cm Green Nitrile Chemical Resistant Gauntlets 40CMMF",
    vendorPartNum: "REL40CMMF",
    manufacturerPartNum: "40CMMF",
    description:
      "Marigold Flexiproof 40cm Green Nitrile Chemical Resistant Gauntlets 40CMMF Mrigold Flexiproof 40 cm The glove is ideal for intensive tasks, handling of abrasive and sharp components, immersion in very aggressive chemicals, including solvents. contact heat up to 100°C Description Good dexterity and flexibility. Improved resistance to abrasion. Great comfort in intensive wear. Ideal Applications Agrochemicals Chemical processing and preparation Defence industry Degreasing Handling acids, caustics and solvents Maintenance Metal fabrication Petrochemicals Public utilities Refining – Oil & Petrol Sub-assembly handling Tank filling",
    brand: "",
    leadTime: "",
    price: 28,
    image: "texas-inventory/glovethick.jpg",
  },
  {
    id: 42,
    title:
      "Uvex Profastrong Chemical-Resistant Safety Gloves with Cotton Flock Lining 100UP",
    vendorPartNum: "REL100UP",
    manufacturerPartNum: "100UP",
    description:
      "Uvex Profastrong Chemical-Resistant Safety Gloves with Cotton Flock Lining Comfortable protection against chemicals, abrasions and other risks Cotton flock lining improves comfort Excellent chemical protection Stops damage from abrasions Chemical protection is essential in environments where hazardous materials are handled. Because of the higher chance of contact, the hands are one of the most important areas to protect, and these chemical-resistant gloves do just that, while keeping the wearer comfortable. The gloves are suitable for use with a range of chemicals, in addition to oils and solvents. They stop dangerous materials from coming into contact with the hands, keeping the wearer safe. The gloves are lined with a cotton flock material, which makes them comfortable to wear and provides a much more pleasant experience when the gloves are worn for long periods of time. In addition to the hands, eyes are at risk in environments with dangerous chemicals. Protect them effectively with our safety goggles.",
    brand: "",
    leadTime: "",
    price: 8.37,
    image: "texas-inventory/uvex.jpg",
  },
  {
    id: 43,
    title: "TitanFlex TGHD119",
    vendorPartNum: "RELTGHD119",
    manufacturerPartNum: "TGHD119",
    description:
      "Thor Grip Heavy Duty Black Industrial Nitrile Gloves TGHD119 Thor Grip Heavy Duty Black Industrial Nitrile Gloves with Raised Diamond Texture, 8-mil, Latex Free, 100-ct Box HEAVY DUTY: TitanFlex 8-mil premium nitrile gloves are 2-3 times thicker than regular disposable nitrile gloves, and provide more puncture resistance and excellent barrier protection against grease, gasoline, and many other petroleum-based chemicals. THOR GRIP DIAMOND TEXTURE: Fully textured fingers and palms with arrayed raised diamond patterns provide 60% more gripping power than regular nitrile gloves, yet with good dexterity for handling small objects and tools even wet or slippery. PROFESSIONAL APPEARANCE: Black gloves conceal dirt, grease, and grime, adding a clean and professional look, ideal for mechanics, automotive repair, oil changes, plumbers, janitorial, construction, manufacturing, police, and law enforcement. LATEX-FREE GLOVES: Free of natural rubber latex, these disposable nitrile gloves help reduce allergic skin reactions to latex and protein; they are elastic, stretchy, and have a snug fit, but provide more chemical resistance than latex gloves. MULTIPURPOSE: HD45K nitrile gloves can be used for various industrial, commercial, and household applications such as mechanics, auto repair, janitorial, painting, plumbing, oil changes, construction, technician, BBQ, and household cleaning.",
    brand: "",
    leadTime: "",
    price: 23.99,
    image: "texas-inventory/glove.jpg",
  },
  {
    id: 44,
    title: "Hard Hat: Yellow",
    vendorPartNum: "RELTGHD119",
    manufacturerPartNum: "TGHD119",
    description:
      "Hard Hat Hard Hat: Yellow, No Graphics, Ratchet (4-Point), Polyethylene, Side-Slots, BULLARD, Basic Colors Brand: BULLARD ANSI Classification: Type 2, Class E Head Protection Style: Front Brim Head Protection Suspension Type: Ratchet (4-Point) Head Protection Graphics: No Graphics Fits Hat Size: 6-1/2 to 8 Head Protection Material: Polyethylene Accessory Mounting Options: Side-Slots Head Protection Venting: No High-Visibility: No Standards: ANSI Z89.1-2009 Suspension Adjustment Type: Ratchet Number of Suspension Points: 4 Application: Work Site Accessory Slots: Yes Head Protection Brand: BULLARD Series: Vector Type II UNSPSC: 46181701",
    brand: "",
    leadTime: "",
    price: 61.63,
    image: "texas-inventory/helmet.jpg",
  },
  {
    id: 45,
    title: "WORK BOOTS AND SHOES",
    vendorPartNum: "RELAT801-2",
    manufacturerPartNum: "",
    description:
      "WORK BOOTS AND SHOES Mens Work Boots, Nubuck Leather Steel Toes Safety Footwear, Slip Resistent YKK Zipper Protective Shoes, 6 inch, Anti-Puncturing, Anti-Static, Lightweight (AT801-2, Black) Sole material: Rubber Outer material: Ethylene Vinyl Acetate (EVA) Closure type: Zipper Water resistance level: Water Repellent What Can the Modaflame Orange Type 6 Welding Jumpsuit Do to Help Me? Lace-up & Ykk Zipper Design: The mens work boots with lace-up and Ykk zipper meet your needs, you are comfortable with the boots. And easying to take off and put on it. Steel Toecap: The fashion & casual work boots for men with premium nubuck leather upper, which conforms to ASTM F2413-18 I/C standards and boasts impact-resistence (200J) and pressure-resistance (15KN). KEVLAR & EVA Midsole: The black men’s work boots are made with KEVLAR and EVA midsole. You don’t need to worry about the sharp objects and puncturing your feet with the KEVLAR midsole, Conforming to ASTM F2413-18 PR. And other side, we use the light weight EVA material into the midsole, which supply excellent cushion for you, you will not feel tired after hard work. Static Disspative Rubber Outsole:The protective mens footwear with anti-static and non-slip rugged rubber outsole, comforms to ASTM F2413-18 SD. Not only preventing you from slipping, and extending the use time. PU Flexible & Comfortable Footbed:The work boots with removable PU insole offer arch support and comfort. The insole will reduce the feet fatigue and absorb the shocking, which protect your feet well.",
    brand: "",
    leadTime: "",
    price: 107.99,
    image: "texas-inventory/shoe.jpg",
  },
  {
    id: 46,
    title: "Power PRC1250XL 12V 55Ah UPS Replacement Battery",
    vendorPartNum: "RELPRC1250XL",
    manufacturerPartNum: "PRC1250XL",
    description:
      "Power PRC1250XL 12V 55Ah UPS Replacement Battery × 10 Specification Product Dimensions: 9.02 x 5.43 x 8.27 inches ASIN: B009DKGKFW Item model number:PRC1250XL Manufacturer: AJC Battery Exact OEM replacement that fits easily and precisely Factory activated, this battery arrives fully sealed, charged and ready for action Built to last",
    brand: "",
    leadTime: "",
    price: 824.027,
    image: "texas-inventory/battery.jpg",
  },
  {
    id: 47,
    title: "New 501 453 UNIV B M25",
    vendorPartNum: "",
    manufacturerPartNum: "New 501 453 UNIV B M25",
    description:
      "New 501 453 UNIV B M25 Brass Gland Flameproof & Increased Safety ATEX / IECEx / UKEX Certified CML 18ATEX1268X IECEx CML 18.0131X CML 21UKEX1132X Temp. Range: -60°C to +80°C IP66 PVC Shroud Black For an M25 SizeCable Gland Hawke Size B Gland",
    brand: "Hawke International",
    leadTime: "",
    price: null,
    image: "texas-inventory/valve.jpg",
  },
  {
    id: 48,
    title: "New 501 453 UNIV O M20",
    vendorPartNum: "",
    manufacturerPartNum: "New 501 453 UNIV B M25",
    description:
      "New 501 453 UNIV O M20 Brass Gland Flameproof & Increased Safety ATEX / IECEx / UKEX Certified CML 18ATEX1268X IECEx CML 18.0131X CML 21UKEX1132X Temp. Range: -60°C to +80°C IP66 PVC Shroud Black (O) For an M20S Size Cable Gland Hawke Size O/OS Gland",
    brand: "Hawke International",
    leadTime: "",
    price: "",
    image: "texas-inventory/valve.jpg",
  },
  {
    id: 49,
    title: "Cable Tray, Heavy Duty",
    vendorPartNum: "",
    manufacturerPartNum: "HR-FB90-150-075R-SS-1.0-K",
    description:
      "Cable Tray, Heavy Duty, 50mm SideWall, Flat Bend 90°, 150mm Wide, 75mm Rad, Grade 1.4404 (316L) Stainless Steel, 1.0mm ",
    brand: "Vantrunk",
    leadTime: "",
    price: null,
    image: "texas-inventory/cablepan.jpg",
  },
  {
    id: 50,
    title: "Cable Tray, Heavy Duty",
    vendorPartNum: "",
    manufacturerPartNum: "HR-SL3-150-SS-1.0-K",
    description:
      "Cable Tray, Heavy Duty, 50mm SideWall, Straight Length, 3000mm Long, 150mm Wide, Grade 1.4404 (316L) Stainless Steel, P&P, 1.0mm",
    brand: "Vantrunk",
    leadTime: "",
    price: null,
    image: "texas-inventory/cablepan.jpg",
  },
  {
    id: 51,
    title: "EVOLUTION X LED FLOODLIGHT 30L",
    vendorPartNum: "EV XB/0230L/LE",
    manufacturerPartNum: "EV XB/30L/LE",
    description:
      "EVOLUTION X LED FLOODLIGHT 30L ZONE 1 & 21 LED FLOODLIGHT DELIVERED OUTPUT: 29433 LM POWER CONSUMPTION: 253W ATEX IECEX UKEX CERTIFIED TYPE OF PROTECTION: EX DB EB & EX TB 2 X M20 ENTRIES 110-277V AC 50/60HZ 127-250V DC IP66/67 MANUFACTURED BY: CHALMIT LIGHTING TARIFF CODE: 94054010",
    brand: "",
    leadTime: "",
    price: null,
    image: "texas-inventory/chalmit.jpg",
  },
  {
    id: 52,
    title: "PROTECTA III FLOURESCENT 2X36W",
    vendorPartNum: "PR GE/02-236/BI",
    manufacturerPartNum: "PR GE/02-236/BI",
    description:
      "PROTECTA III FLOURESCENT 2X36W ZONE 1 & 21 BI-PIN FLOURESCENT ATEX & IECEX CERTIFIED II 2 G D EX E MB Q IIC EX T B IIIC DB IP66 T4 GB TAMB -20° TO +55° T85°C 4 X M20 ENTRIES 2 AT EACH END 3 CORE 4MM² MAX CONDUCTOR WITH LOOPING AND 16A RATING THROUGH WIRING IP66/67 MANUFACTURED BY: CHALMIT LIGHTING TARIFF CODE: 94054010",
    brand: "",
    leadTime: "",
    price: null,
    image: "texas-inventory/long.jpg",
  },
  {
    id: 53,
    title: "PLUGS 16 A SERIES 8570/12",
    vendorPartNum: "RE272898",
    manufacturerPartNum: "272898",
    description: "PLUGS 16 A SERIES 8570/12 8570/12-306-S-XX-X-XX-XXX-ZAN ",
    brand: "STAHL",
    leadTime: "",
    price: null,
    image: "texas-inventory/fs.jpg",
  },
  {
    id: 54,
    title: "WALL-MOUNTING SOCKETS 16 A SERIES",
    vendorPartNum: "RE273935",
    manufacturerPartNum: "273935",
    description:
      "WALL-MOUNTING SOCKETS 16 A SERIES 8570/11-306-S-01-0-00-XXX-ZAN",
    brand: "STAHL",
    leadTime: "",
    price: null,
    image: "texas-inventory/fs.jpg",
  },
  {
    id: 55,
    title: "Kubota Complete Cylinder Head Kit",
    vendorPartNum: "rel-230250",
    manufacturerPartNum: "273935",
    description:
      "Complete Cylinder Head Comes With The Below: 8 Seal Heat 8 Washer 8 Gasket Copper 2 Pipe Water return 2 Assy Thermostat 2 Gasket Thermostat 2 Gasket w/Flange 4 Gasket Muffler 2 Gasket Ex-Manifold 2 Gasket In-Manifold 2 Gasket Head Co 2 Gasket Cylinder Head",
    brand: "Kubota",
    leadTime: "4-6 weeks ex works",
    price: 16060,
    image: "texas-inventory/block.jpg",
  },
  {
    id: 56,
    title: "Lenovo 14″ ThinkPad X1 Yoga Gen 8",
    vendorPartNum: "RE-2023239-LEV",
    manufacturerPartNum: "21HQ0007US",
    description:
      "Processor：13th Generation Intel® Core™ i7-1355U Processor (E-cores up to 3.70 GHz P-cores up to 5.00 GHz) Operating System：Windows 11 Pro 64 Graphic Card：Integrated Intel® Iris® Xe Graphics Memory：16 GB LPDDR5-6400MHz (Soldered) Storage：512 GB SSD M.2 2280 PCIe Gen4 Performance TLC Opal Display：14″ WUXGA (1920 x 1200), IPS, Anti-Glare, Touch, 100%sRGB, 400 nits, 60Hz, LED Backlight, Narrow Bezel, Low Blue Light Camera：1080P FHD with Privacy Shutter and Integrated Microphone Fingerprint Reader：Fingerprint Reader Pointing Device：TouchpadLenovo Digital Pen Keyboard：Backlit, Grey – English (US) WLAN：Intel® Wi-Fi 6E AX211 2×2 AX & Bluetooth® 5.1 or above WWAN：None Warranty：One Year Onsite",
    brand: "",
    leadTime: "In Stock",
    price: 1900,
    image: "texas-inventory/lap.jpg",
  },
  {
    id: 57,
    title: "BIFOLD LIFT GATE ON A 2022 CHEVROLET 3500",
    vendorPartNum: "RE-2023220",
    manufacturerPartNum: "MAXC2-87-1650 EA41",
    description:
      "LIGHT DUTY SERIES C2 Stakebed & Van Body Bifold lift gate on a 2022 Chevrolet 3500 Vin # 1GB4WRE79NF299555 that has a flat bed Equipment Specifications: 1600lb. Capacity C2-87-1650 EA41+6ª RAMP,W/INSTL KIT ALUMINUM Platform . • Lift gate Capacity- 1,600 LBS • Dual hydraulic lifting cylinders • Maintenance-free components • Protected / recessed main control with time-out feature • Aluminum platforms • Fully-enclosed hydraulic system Patent Pending Pre-punched Holes for Camera/Sensors • Gravity down only Install Maxon C2 liftgate, 1600 lb capacity. Applicable for 92″ Wide Bodies",
    brand: "",
    leadTime: "",
    price: 9670,
    image: "texas-inventory/IMG5.jpg",
  },
  {
    id: 58,
    title: "VIP VEGAS 3 STATION",
    vendorPartNum: "RE-2023233",
    manufacturerPartNum: "",
    description:
      "Three Station Vegas Restroom Trailer Here is what the 3 station Vegas offers: • Men’s and Women’s room • 3 Stalls • 3 Sinks • 1 Urinal • Central air conditioning and heat • Luxurious lighting • LED exterior lights • Elegant marble-finish sinks • Elegant two tone light color interior • Beautiful dark hardwood floors • Complete music and sound systems • Large mirrors • Skylights •150 gallon fresh water tank Manufacturer: VIP Vegas 3 station",
    brand: "",
    leadTime: "",
    price: 66700,
    rental: 7151.95,
    image: "texas-inventory/vip.png",
  },
  {
    id: 59,
    title:
      "RELI2023XCM/247 3’RFP1-3F03-1 |1N [SM100Mbps 1310nm 20km], the S/N: I81072247",
    vendorPartNum: "RELI2023XCM/247",
    manufacturerPartNum: "SFP-3’RFP1-3F03-1I1Y, SFP-3’RFP1-3F03-1I1N",
    description:
      "3’RFP1-3F03-1 |1N [SM100Mbps 1310nm 20km], the S/N: I81072247",
    brand: "",
    leadTime: "",
    price: 220,
    rental: null,
    image: "texas-inventory/Screenshot-378.jpg",
  },
  {
    id: 60,
    title:
      "RELI2024XCM 2022 Intimidator 1000cc 4×4 Classic 4WD utility vehicle",
    vendorPartNum: "RELI2024XCM",
    manufacturerPartNum: "",
    description:
      "1000cc 24HP diesel engine 12″ ground clearance rollover protective structure (ROPS) approved chassis cage 4500lb wire rope winch 2100lb towing capacity 1600lb payload capacity 27″ tires on 14″ steel wheels 3 occupant bench seat",
    brand: "",
    leadTime: "",
    price: null,
    rental: null,
    image: "texas-inventory/Screenshot.jpg",
  },
  {
    id: 61,
    title:
      "RELI2023XCM 6 Port Gigabit and 10/100 Mbps Ethernet Self-managed Switch 2 SFP FX, 4TX",
    vendorPartNum:
      "RELI2023XCM (Please note: Part Number fully tested and approved by the State of Texas) do not substitute part number)!",
    manufacturerPartNum: "ComNet/CommNet Model: CNGE2FE4SMS",
    description:
      "6 Port Gigabit and 10/100 Mbps Ethernet Self-managed Switch 2 SFP FX, 4TX [IMPORTANT: DC Plug-in Power Supply, 90-264 VAC, 50-60 Hz included with 10Mbps/ 100Mbps and 10000Mbps Power source and SFP included",
    brand: "",
    leadTime: "",
    price: 1700,
    rental: null,
    image: "texas-inventory/comnet.jpg",
  },
];

export default texasInventory;
